//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTime
    {
        public int CourseTimeID { get; set; }
        public string Type { get; set; }
        public Nullable<int> FKCourseID { get; set; }
        public Nullable<System.DateTime> CourseTime1 { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
