//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.CourseWeeks = new HashSet<CourseWeek>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string SchoolCourseCode { get; set; }
        public string CourseWeeksID { get; set; }
        public string Semester { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CourseTimesID { get; set; }
    
        public virtual ICollection<CourseWeek> CourseWeeks { get; set; }
    }
}
