//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PM_Entities : DbContext
    {
        public PM_Entities()
            : base("name=PM_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cours> Courses { get; set; }
        public DbSet<CourseTime> CourseTimes { get; set; }
        public DbSet<CourseWeek> CourseWeeks { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<TaskComment> TaskComments { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TeamMember> TeamMembers { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TemplateTask> TemplateTasks { get; set; }
    }
}
