//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> TaskStartTime { get; set; }
        public System.DateTime TaskDeadline { get; set; }
        public Nullable<int> FKTeamID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> FK_AssigneeID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Team Team { get; set; }
    }
}
