//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Tasks = new HashSet<Task>();
            this.TeamMembers = new HashSet<TeamMember>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> FK_CourseID { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
    }
}
