//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateTask
    {
        public int TemplateTasksID { get; set; }
        public Nullable<int> FK_TemplateID { get; set; }
        public byte[] Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> Deadline { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
