//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomMembershipEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.TemplateTasks = new HashSet<TemplateTask>();
        }
    
        public int TemplateID { get; set; }
        public string CourseID { get; set; }
    
        public virtual ICollection<TemplateTask> TemplateTasks { get; set; }
    }
}
