<?xml version="1.0" encoding="utf-8"?><Database Name="PM" Class="TaskDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=54.218.14.4;Initial Catalog=PM;User ID=sa" SettingsObjectName="EventNotifier.Properties.Settings" SettingsPropertyName="PMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaskName" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TaskDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TaskStartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TaskDeadline" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FKTeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_AssigneeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="alerted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>